version: "3.7"
services:
  serv-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: pokemon
      MYSQL_USER: userlaravel
      MYSQL_PASSWORD: user1234
    ports:
      - 3306:3306
    volumes:
      - ./databases/schemas:/var/lib/mysql
    networks:
      laravel_prod_net:
        ipv4_address: 173.22.100.9

  serv-laravel:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - 8200:80
    volumes:
      - ./:/var/www/
      - ./public:/var/www/html
    networks:
      laravel_prod_net:
        ipv4_address: 173.22.100.10
    depends_on:
      - serv-mysql

volumes:
  Pokemon:  
  database:      
networks:
  laravel_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 173.22.100.0/24